# Generated by Django 4.2.3 on 2023-07-30 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=16384, null=True)),
                ('complete', models.BooleanField(blank=True, default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_attached', models.BooleanField(blank=True, default=False)),
                ('priority', models.CharField(blank=True, choices=[('ahigh_priority', 'Высокий'), ('bmedium_priority', 'Средний'), ('clow_priority', 'Низкий'), ('dlowest_priority', 'Самый низкий'), ('edefault', 'Обычный')], default='edefault', max_length=30)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
